"""create docker_metrics table

Revision ID: 278c8ed5c4f5
Revises: ffd0de8ef6dc
Create Date: 2026-05-02 18:57:38.448625

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "278c8ed5c4f5"
down_revision: str | Sequence[str] | None = "ffd0de8ef6dc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "docker_metrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("server_id", sa.Integer(), nullable=False),
        sa.Column("container_id", sa.String(), nullable=False),
        sa.Column("container_name", sa.String(), nullable=False),
        sa.Column("image", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("cpu_percent", sa.Float(), nullable=False),
        sa.Column("memory_usage_mb", sa.Float(), nullable=False),
        sa.Column("memory_limit_mb", sa.Float(), nullable=True),
        sa.Column(
            "collected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["server_id"],
            ["servers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_docker_metrics_server_id_collected_at",
        "docker_metrics",
        ["server_id", "collected_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_docker_metrics_server_id_collected_at", table_name="docker_metrics")
    op.drop_table("docker_metrics")
    # ### end Alembic commands ###
