"""add owner_id to servers

Revision ID: 62b88e6c93af
Revises: d432b550632e
Create Date: 2026-05-01 11:11:55.784699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62b88e6c93af'
down_revision: Union[str, Sequence[str], None] = 'd432b550632e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'servers', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'servers', type_='foreignkey')
    op.drop_column('servers', 'owner_id')
    # ### end Alembic commands ###
