"""add email_alerts_enabled to users

Revision ID: 971107cbe3a8
Revises: ab2eb4bc624c
Create Date: 2026-05-06 21:42:35.434876

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "971107cbe3a8"
down_revision: str | Sequence[str] | None = "ab2eb4bc624c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("email_alerts_enabled", sa.Boolean(), server_default="true", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "email_alerts_enabled")
    # ### end Alembic commands ###
