"""add container_name to alert_events

Revision ID: ab2eb4bc624c
Revises: 54db233075d4
Create Date: 2026-05-06 21:18:14.613759

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ab2eb4bc624c"
down_revision: str | Sequence[str] | None = "54db233075d4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("alert_events", sa.Column("container_name", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("alert_events", "container_name")
    # ### end Alembic commands ###
