"""add resolved_at to alert_events

Revision ID: b3ee6f8a901f
Revises: d0d1001ee097
Create Date: 2026-05-06 15:06:40.281168

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b3ee6f8a901f"
down_revision: str | Sequence[str] | None = "d0d1001ee097"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "alert_events", sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("alert_events", "resolved_at")
    # ### end Alembic commands ###
